# Generated by Django 4.2.3 on 2023-07-21 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام دسته بندی ')),
                ('slug', models.CharField(max_length=100, verbose_name='نام دسته بندی ')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی ها ',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.FileField(upload_to='Images_project/', verbose_name='عکس سر تیتر 1 ')),
                ('pic2', models.FileField(upload_to='Images_project/', verbose_name='عکس سر تیتر 2 ')),
                ('pic3', models.FileField(upload_to='Images_project/', verbose_name='عکس سر تیتر 3 ')),
                ('title', models.CharField(max_length=100, verbose_name='نام پروژه')),
                ('customer', models.CharField(max_length=100, verbose_name='مشتری')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('body', models.TextField(verbose_name='متن ')),
                ('slug', models.SlugField(verbose_name='آدرس اینترنتی ')),
                ('type_project', models.CharField(choices=[('Design', 'طراحی'), ('Repairs', 'تعمیرات'), ('Construction', 'ساخت '), ('Remodeling', 'بازسازی')], max_length=20, verbose_name='نوع پروژه')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Total_project.category', verbose_name='دسته بندی ')),
            ],
            options={
                'verbose_name_plural': 'پروژه های شرکت ',
                'db_table': 'project',
            },
        ),
    ]
