# Generated by Django 4.2.3 on 2023-07-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='message_creator',
            field=models.TextField(null=True, verbose_name=' متن نویسنده '),
        ),
    ]
