# Generated by Django 4.2.3 on 2023-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_project', '0002_project_message_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type_project',
            field=models.CharField(choices=[('filter-design', 'طراحی'), ('filter-repairs', 'تعمیرات'), ('filter-construction', 'ساخت '), ('filter-remodeling', 'بازسازی')], max_length=20, verbose_name='نوع پروژه'),
        ),
    ]
