# Generated by Django 4.2.3 on 2023-07-21 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Total_project', '0003_alter_project_type_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictur', models.FileField(upload_to='Image_slider/', verbose_name='عکس ')),
                ('sentnce', models.CharField(max_length=300, verbose_name='جمله')),
            ],
            options={
                'verbose_name_plural': 'عکس های اسلایدر ',
                'db_table': 'Slider_Index',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=100, verbose_name=' آدرس اینترنتی  '),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
