# Generated by Django 4.2.3 on 2023-07-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Total_project', '0005_rename_sentnce_slider_index_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider_index',
            old_name='pictur',
            new_name='picture',
        ),
    ]
