# Generated by Django 4.2.3 on 2023-07-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_project', '0006_rename_pictur_slider_index_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Data_Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=12, verbose_name='تلفن')),
                ('message', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name_plural': 'ارسال نظر ',
                'db_table': 'Send_Data_Quote',
            },
        ),
    ]
