# Generated by Django 4.2.3 on 2023-07-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Total_project', '0007_send_data_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client_register', verbose_name='نام نویسنده')),
            ],
        ),
    ]
