# Generated by Django 4.2.3 on 2023-07-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Total_project', '0008_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'جملات برای نظر در مورد سایت '},
        ),
        migrations.AddField(
            model_name='testimonials',
            name='sentence',
            field=models.TextField(null=True, verbose_name='جمله '),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client_register', verbose_name='نام نویسنده'),
        ),
        migrations.AlterModelTable(
            name='testimonials',
            table='Testimonials',
        ),
    ]
