# Generated by Django 4.2.3 on 2023-07-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_client_register_position'),
        ('Total_project', '0009_alter_testimonials_options_testimonials_sentence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client_register', verbose_name='نویسنده'),
        ),
    ]
