# Generated by Django 4.2.3 on 2023-07-30 11:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_project', '0010_alter_project_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='Images_Service/', verbose_name='تصویر ')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان خدمت')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن اصلی')),
                ('text_slide', models.TextField(verbose_name='متن کناری')),
                ('type_service', models.CharField(choices=[('طراحی', 'طراحی'), ('تعمیرات', 'تعمیرات'), ('ساخت ', 'ساخت '), ('بازسازی', 'بازسازی')], max_length=100, verbose_name='دسته خدمت')),
            ],
            options={
                'verbose_name_plural': 'خدمات شرکت',
                'db_table': 'Services',
            },
        ),
    ]
