# Generated by Django 4.2.3 on 2023-07-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_project', '0011_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDRESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس ما ')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل ما')),
                ('phone', models.CharField(max_length=13, verbose_name='تلفن ما ')),
            ],
            options={
                'verbose_name_plural': 'آدرس ما ',
                'db_table': 'ADDRESS',
            },
        ),
    ]
