# Generated by Django 4.2.3 on 2023-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_project', '0012_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='phone1',
            field=models.CharField(max_length=13, null=True, verbose_name='1تلفن ما '),
        ),
        migrations.AddField(
            model_name='address',
            name='phone2',
            field=models.CharField(max_length=13, null=True, verbose_name='2تلفن ما '),
        ),
    ]
