# Generated by Django 4.2.3 on 2023-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total_project', '0013_remove_address_phone_address_phone1_address_phone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(max_length=100, verbose_name='پیام')),
            ],
            options={
                'verbose_name_plural': 'پیام های ارسال شده از طریق فرم ارتباط با ما',
                'db_table': 'contact_us',
            },
        ),
    ]
