# Generated by Django 4.2.3 on 2023-07-21 12:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dasteh_bandy_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='آدرس اینترنتی ')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی ها ',
                'db_table': 'dasteh_bandy',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='آدرس اینترنتی ')),
            ],
            options={
                'verbose_name_plural': 'تگ ها ',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('text', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('dasteh_bandy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.dasteh_bandy_model', verbose_name='دسته بندی ')),
                ('tags', models.ManyToManyField(to='blog.tag', verbose_name='تگ ها ')),
            ],
            options={
                'verbose_name_plural': 'بلاگ ها ',
                'db_table': 'Blogs',
            },
        ),
    ]
