# Generated by Django 4.2.3 on 2023-07-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dasteh_bandy_model',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='آدرس اینترنتی '),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='آدرس اینترنتی '),
        ),
    ]
