# Generated by Django 4.2.3 on 2023-07-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_client_register_position'),
        ('blog', '0003_blogs_head_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client_register', verbose_name='نویسنده'),
        ),
    ]
