# Generated by Django 4.2.3 on 2023-07-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogs_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('website', models.SlugField(blank=True, null=True, verbose_name='وب سایت')),
                ('message', models.TextField(verbose_name='پیام ')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogs', verbose_name='بلاگ')),
            ],
            options={
                'verbose_name_plural': 'کامنت ها ',
                'db_table': 'comments',
            },
        ),
    ]
