# Generated by Django 4.2.3 on 2023-07-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_register',
            name='position',
            field=models.CharField(choices=[('master', 'مدیر فنی'), ('employee', 'کارمند'), ('m-fan', 'مدیر اجرایی')], max_length=100, null=True, verbose_name='سمت '),
        ),
    ]
