# Generated by Django 4.2.3 on 2023-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_client_register_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_register',
            name='position',
            field=models.CharField(choices=[('مدیر فنی', 'مدیر فنی'), ('کارمند', 'کارمند'), ('مدیر اجرایی', 'مدیر اجرایی')], max_length=100, null=True, verbose_name='سمت '),
        ),
    ]
