# Generated by Django 4.2.3 on 2023-07-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_client_register_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='faceboob',
            field=models.SlugField(null=True, verbose_name='لینک فیسبوک'),
        ),
        migrations.AddField(
            model_name='client_register',
            name='instagram',
            field=models.SlugField(null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='client_register',
            name='twitter',
            field=models.SlugField(null=True, verbose_name='لینک توئیتر'),
        ),
    ]
