# Generated by Django 4.2.3 on 2023-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_client_register_faceboob_client_register_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_register',
            name='faceboob',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='لینک فیسبوک'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='client_register',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='لینک توئیتر'),
        ),
    ]
