# Generated by Django 4.2.3 on 2023-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_alter_client_register_faceboob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='fields',
            field=models.CharField(max_length=100, null=True, verbose_name='زمینه تخصصی'),
        ),
    ]
