# Generated by Django 4.2.3 on 2023-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_client_register_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_register',
            name='about_user',
            field=models.CharField(max_length=300, null=True, verbose_name='درباره عضو'),
        ),
    ]
