# Generated by Django 4.2.3 on 2023-07-29 19:31

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_client_register_about_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', ckeditor.fields.RichTextField(verbose_name='اطلاعات تاریخچه')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شکل گیری')),
                ('picture', models.FileField(upload_to='Image_History/', verbose_name='عکس')),
            ],
            options={
                'verbose_name_plural': 'تاریخچه وبسایت و شرکت',
                'db_table': 'History_website',
            },
        ),
    ]
