# Generated by Django 4.2.3 on 2023-07-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_history_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_website',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
